### PR TITLE
python3 fix, requirements, Dockerfile

### PR DESCRIPTION
**Pull request by nbeguier**
**Features**:
  - requirements.txt up-to-date
  - settings.conf file to manage mongodb
  - /health
  - Replace print by the werkzeug logger function
  - Variabilize the report api path : `-e REPORT_API_PATH=/foo/bar/report` in gunicorn 

**Fixtures**:
  - decode request.data (bytes, not str)
  - "about" could be a document_uri => Respond 204 immediatly

### CODE REVIEW

**Comment by nbeguier** [comment]
Should I improve my PR ? I'm open to suggestions

**Comment by finalduty** [comment]
Hey Nicolas,

Thank you so much for your PR and sorry for not responding sooner.

I'm in the middle of compliance work at the moment 😩 with no spare time but will review this as soon as I can - Hopefully later this week.

**Comment by nbeguier** [comment]
No problem ;)

**Comment by nbeguier** [comment]
I have re-implemented the gunicorn support, and other stuffs.

**Pull request closed without merging**
